### ISSUE TITLE
Add job card pop-up

### ISSUE THREAD

**Issue by emmalangstrom** [justarrived/justarrived.github.io#78]
Pop-up for when you click the job card section.

Button 1: Log in page for service
Button 2: Newcomer application form
Button 3: Email to relevant person or contact page. 

![pop-up](https://cloud.githubusercontent.com/assets/22611328/19350625/d02db26e-9158-11e6-803b-9e0cdfad387f.png)

Heading H3.
Text 16 px.
Subheading 20 px Museo sans.

Close icon:
![close-icon](https://cloud.githubusercontent.com/assets/22611328/19351105/b16f9516-915a-11e6-92ac-0c65d9e28975.png)

**Comment by buren** [comment]
@emmalangstrom finally got around implementing this :) https://github.com/justarrived/justarrived.github.io/pull/94

There are some slight differences from your specification above:
1. I placed the "Log in" button at the bottom since we still don't have a ton of users with accounts (yet) and that many have misunderstood Wintrgarden vs Just Arrived. 
2. I also did some slight copy changes (lets discuss those too 👍)
3. Haven't changed the close-icon
4. The text sizes aren't changed (I'm using the same CSS for this and other popups..)

I'll open a separate issue for updating the popup styling (https://github.com/justarrived/justarrived.github.io/issues/95), so we can release this feature and then iterate on the exact popup design later :) (There are so many that click on the job cards so we really need this popup shipped :shipit:)
